# Generated by Django 3.2.11 on 2022-06-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='licence',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Real Estate Licence'),
        ),
    ]
